services:
    db:
        container_name: postgres_container
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=test_db
        ports:
            - 5432:5432

    adminer:
        container_name: postgres_admin
        image: adminer
        restart: always
        ports:
            - 8082:8080
